export type ComponentItem = {
  id: string
  name: string
  path: string
}

export const componentItems: ComponentItem[] = [
  { id: "accordion", name: "Accordion", path: "/components/accordion" },
  { id: "alert", name: "Alert", path: "/components/alert" },
  { id: "alert-dialog", name: "Alert Dialog", path: "/components/alert-dialog" },
  { id: "aspect-ratio", name: "Aspect Ratio", path: "/components/aspect-ratio" },
  { id: "avatar", name: "Avatar", path: "/components/avatar" },
  { id: "badge", name: "Badge", path: "/components/badge" },
  { id: "breadcrumb", name: "Breadcrumb", path: "/components/breadcrumb" },
  { id: "button", name: "Button", path: "/components/button" },
  { id: "button-group", name: "Button Group", path: "/components/button-group" },
  { id: "calendar", name: "Calendar", path: "/components/calendar" },
  { id: "card", name: "Card", path: "/components/card" },
  { id: "carousel", name: "Carousel", path: "/components/carousel" },
  { id: "chart", name: "Chart", path: "/components/chart" },
  { id: "checkbox", name: "Checkbox", path: "/components/checkbox" },
  { id: "collapsible", name: "Collapsible", path: "/components/collapsible" },
  { id: "combobox", name: "Combobox", path: "/components/combobox" },
  { id: "command", name: "Command", path: "/components/command" },
  { id: "context-menu", name: "Context Menu", path: "/components/context-menu" },
  { id: "date-picker", name: "Date Picker", path: "/components/date-picker" },
  { id: "dialog", name: "Dialog", path: "/components/dialog" },
  { id: "drawer", name: "Drawer", path: "/components/drawer" },
  { id: "dropdown-menu", name: "Dropdown Menu", path: "/components/dropdown-menu" },
  { id: "empty", name: "Empty", path: "/components/empty" },
  { id: "field", name: "Field", path: "/components/field" },
  { id: "hover-card", name: "Hover Card", path: "/components/hover-card" },
  { id: "input", name: "Input", path: "/components/input" },
  { id: "input-group", name: "Input Group", path: "/components/input-group" },
  { id: "input-otp", name: "Input OTP", path: "/components/input-otp" },
  { id: "item", name: "Item", path: "/components/item" },
  { id: "kbd", name: "Kbd", path: "/components/kbd" },
  { id: "label", name: "Label", path: "/components/label" },
  { id: "menubar", name: "Menubar", path: "/components/menubar" },
  { id: "native-select", name: "Native Select", path: "/components/native-select" },
  {
    id: "navigation-menu",
    name: "Navigation Menu",
    path: "/components/navigation-menu",
  },
  { id: "pagination", name: "Pagination", path: "/components/pagination" },
  { id: "popover", name: "Popover", path: "/components/popover" },
  { id: "progress", name: "Progress", path: "/components/progress" },
  { id: "radio-group", name: "Radio Group", path: "/components/radio-group" },
  { id: "resizable", name: "Resizable", path: "/components/resizable" },
  { id: "scroll-area", name: "Scroll Area", path: "/components/scroll-area" },
  { id: "select", name: "Select", path: "/components/select" },
  { id: "separator", name: "Separator", path: "/components/separator" },
  { id: "sheet", name: "Sheet", path: "/components/sheet" },
  { id: "skeleton", name: "Skeleton", path: "/components/skeleton" },
  { id: "slider", name: "Slider", path: "/components/slider" },
  { id: "sonner", name: "Sonner", path: "/components/sonner" },
  { id: "spinner", name: "Spinner", path: "/components/spinner" },
  { id: "switch", name: "Switch", path: "/components/switch" },
  { id: "table", name: "Table", path: "/components/table" },
  { id: "tabs", name: "Tabs", path: "/components/tabs" },
  { id: "textarea", name: "Textarea", path: "/components/textarea" },
  { id: "toggle", name: "Toggle", path: "/components/toggle" },
  { id: "toggle-group", name: "Toggle Group", path: "/components/toggle-group" },
  { id: "tooltip", name: "Tooltip", path: "/components/tooltip" },
]
